# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b47096dc0d0771b8f97068e9c54d350661454ba7ff5cf6574e38d78a2bc30770fc6fcfb1e64a9009069926f7023faaaf45b4d86d1240a4013897cfeba179f5

test:
  secret_key_base: cee0f0839a96ff4828c195bd9808671ebab78062f3908d9da7a87cd201b4ba4b3fa47aff801f5fd3f96c6846cc61699189661e1341a9c291d6806e5585ad0c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
